import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from "next/router"
import { useEffect } from 'react';

export default function Home() {
  const router = useRouter();
  
  useEffect(() => {
    const username = localStorage.getItem("chat-app-username");
    username ? router.push("/chat") : router.push("/login")
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Chat-App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          Loading...
        </div>
      </main>
    </div>
  )
}
